apiVersion: apps/v1
kind: Deployment
metadata:
  name: myip4-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yolo_app
  template:
    metadata:
      labels:
        app: yolo_app
    spec:
      containers:
      - name: <container-name>
        image: <your-dockerhub-username>/<image-name>:<tag>
        ports:
        - containerPort: 80
