version: '3.9'
services:
  frontend:
    image: amwayiallan/client-img:latest
    ports:
      - "80:80"

  backend:
    image: amwayiallan/backend-img:latest
    ports:
      - "5000:5000"
    volumes:
      - backend-data:/backend/app/data
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  backend-data: {}
  mongodb-data: {}


