version: '3.9'
services:
  frontend:
    image:amwayiallan/client-img:latest
    ports:
      -"8080:80"

  backend:
    image:amwayiallan/backend-img:latest
    ports:
      -"3000:3000"

  volumes:
    -backend-data:/backend/app/data
    depends_on:
      -"mongodb"

  mongodb:
    image:mongodb
    ports:
      -"27017:27017"
    volumes:
    -mongodb-data:/data/db

volumes:
  backend-data:
  mongodb-data:

