apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: myip4-statefulset
spec:
  selector:
    matchLabels:
      app: yolo_app
  serviceName: myip4-service
  replicas: 2
  template:
    metadata:
      labels:
        app: yolo_app
    spec:
      containers:
      - name: myapp
        image: registry.k8s.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
